export const IMG_TAKEN = 'IMG_TAKEN'

export const POST_CHALLENGE = 'POST_CHALLENGE'
export const POST_CHALLENGE_RESULT = 'POST_CHALLENGE_RESULT'

export const GET_CHALLENGE_LIST = 'GET_CHALLENGE_LIST'
export const GET_CHALLENGE_LIST_RESULT = 'GET_CHALLENGE_LIST_RESULT'

export const GET_FRIENDS_LIST = 'GET_FRIENDS_LIST'
export const GET_FRIENDS_LIST_RESULT = 'GET_FRIENDS_LIST_RESULT'