export const IMG_TAKEN = 'IMG_TAKEN'

export const POST_CHALLENGE = 'POST_CHALLENGE'
export const POST_CHALLENGE_RESULT = 'POST_CHALLENGE_RESULT'

export const GET_CHALLENGE_LIST = 'GET_CHALLENGE_LIST'